id: IF87FD038
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:04:14+00:00'
last_modified: '2022-06-08T10:53:16.232758+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016793
  title: བླ་མ་རིན་པོ་ཆེ་སངས་རྒྱས་ལུང་ཞལ་བཞེས་པའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5851':
      image_group_id: I00EGS1016807
      title: ''
      total_pages: 20
      order: 1
      base_file: 5851.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
