id: IF87FD038
legacy_id: P009417
ocr_import_info:
  bdrc_scan_id: W00EGS1016793
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T22:04:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:17:07.847768+00:00'
last_modified: 2022-08-29 18:17:21.640448
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016793
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016793
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་རིན་པོ་ཆེ་སངས་རྒྱས་ལུང་ཞལ་བཞེས་པའི་རྣམ་ཐར།
  author: སངས་རྒྱས་མཉན་པ ༠༡་བཀྲ་ཤིས་དཔལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.5392302433681986
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I00EGS1016807:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016807
      total_pages: 20
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016807.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5392302433681986
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
