id: P009417
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016793
  title: བླ་མ་རིན་པོ་ཆེ་སངས་རྒྱས་ལུང་ཞལ་བཞེས་པའི་རྣམ་ཐར
  author: ''
  volumes:
    382c5a15fe714566a0f4402acc55ec9e:
      image_group_id: I00EGS1016807
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
